### ISSUE TITLE
Various errors for Visualizer block when using FSE

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/visualizer#1015]
### Description

https://vertis.d.pr/i/4J5mtJ

### Step-by-step reproduction instructions

1. Use a FSE theme
2. Click on Edit site
3. Add the Visualizer block -> various errors appear in the console, and you can't see the charts

### Is the issue you are reporting a regression

No

**Comment by girishpanchal30** [comment]
Hey @HardeepAsrani,

For this Gutenberg FSE related issue, I need your help here.

In the FSE editor, the visualizer block assets are not enqueued and I try to find out the reason behind this issue but I can't find out the reason.
Ref: https://tinyurl.com/2q9yexn9

Here is Gutenberg block code: https://github.com/Codeinwp/visualizer/blob/master/classes/Visualizer/Gutenberg/Block.php#L60

Please tell me if you have any idea about this issue.

Thanks

**Comment by HardeepAsrani** [comment]
@girishpanchal30 That is happening because FSE editor loads inside an iFrame. The same will happen if you use Visualizer in a normal post and Preview them as Tablet or Mobile.

<img width="2560" alt="Screenshot 2023-05-05 at 2 14 57 AM" src="https://user-images.githubusercontent.com/2649903/236325120-fd84c8fb-9623-42e3-96a4-b42345b489c5.png">

Normally the style should load properly if you use Gutenberg's recommended method of https://developer.wordpress.org/reference/functions/register_block_type_from_metadata/ to enqueue styles.

For the scripts, we use a utility function to copy the scripts to iFrame: https://github.com/Codeinwp/otter-blocks/blob/fda6228e869b3875733dbfdcce945b57abb97d50/src/blocks/helpers/block-utility.js#L406-L436

Let me know if it helps.

**Comment by girishpanchal30** [comment]
@HardeepAsrani Thank you for the explanation, I will check and let you know if I require any assistance.

**Comment by girishpanchal30** [comment]
Hey @HardeepAsrani,

I've applied your suggestion and it seems working fine for the block style but still Google Chart JS not working in the FSE editor.
Ref: https://tinyurl.com/2ex4kslr - getting this error in the console bar

Now I've used the block.json method to fix the style/script issue, but it seems removed the chart edit control.
Ref: https://tinyurl.com/2qbk2daw
Before: https://tinyurl.com/2n38kswx

It seems to happen because of `div[data-type="visualizer/chart"]` element is not added when we use the block.json method.

Please review this attached PR when you have a moment.

Thanks

**Comment by HardeepAsrani** [comment]
@girishpanchal30 I tried to take a look but given the amount of code and scripts loaded, it's not a quick debug. Based on my test, I think some Google API scripts isn't loaded properly or React Charts component is somewhere still binded to the main window and trying to find the chart there. Best bet would be to just remove everything and trying to debug this issue with a single ReactChart component and dummy data and see what is being loaded and what is required.

**Comment by girishpanchal30** [comment]
Hey @HardeepAsrani,

I test a single chart with dummy data and found the same error.
You can check with the attached demo-chart plugin - https://github.com/Codeinwp/visualizer/files/11417664/chart-demo.zip

Thanks

**Comment by HardeepAsrani** [comment]
Hey @girishpanchal30,

Thanks for the demo plugin, it was easier to experiment with this. With this it was easy to know the issue is with the component we use: https://github.com/rakannimer/react-google-charts/issues/322#issuecomment-752050819

It's a known issue and isn't really with the component but Google API which tries to access the Chart instance and can't find it. Unless we find something crazy and creative to solve this, it won't really work. Or we will need to drop the Component and try to recreate the chart API, which will have better chance of fixing but will take too much time. I tried few tricks to see if something quick can work but no luck.

I'd suggest that we can, for now, just don't show it FSE or responsive modes and just show a placeholder saying (different for both) saying:

- In FSE, they can't view the chart from here, link to Visualizer page's edit.
- In Responsive mode, they need to switch to Desktop to view it.

This will be my recommendation for a quick solution as it's been an issue forever and so far only one customer has reported it. I think @vytisbulkevicius take the call on next step.

**Comment by girishpanchal30** [comment]
@HardeepAsrani Thank you for the review and suggestions.

**Comment by vytisbulkevicius** [comment]
Thanks for your work here @HardeepAsrani and @girishpanchal30.

I agree with Hardeep that we can add a notice if it's FSE Editor that the selection of a chart is not available, use shortcode instead. 

But the issue doesn't occur for me on mobile/tablet view of regular posts, does it happen for you @rodica-andronache?

**Comment by girishpanchal30** [comment]
Hey @vytisbulkevicius, @rodica-andronache,

Added chart unavailable notice for FSE editor only, please check with the latest commit and let me know if need any changes.
Ref: https://tinyurl.com/2pvaczuk

Thanks

**Comment by rodica-andronache** [comment]
@girishpanchal30 everything's working well 👍
