### ISSUE TITLE
Reuse Shortcode on same page

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/visualizer#124]
@selul is there any particular reason shortcodes can't be populated twice on the page without needing to duplicate the chart to create a new shortcode?

I know it uses IDs to know which chart to display but is there any specific reason why the same shortcode can't be generated more than once on a page? A client asked this

**Comment by selul** [comment]
@contactashish13 can you please take care of this ? In order to replicate the bug, duplicate the same shortcode in the editor. 

i think there is an issue with using the same id of the chart in the page, we could use a helper method for generating the id, it will receive the actual id of the visualizer and will return the id which we will use in the page. basically the new id can be a concatenation of visualizer_id + no_of_appearance, smth like 44-1 44-2, etc. We will use the helper method to keep track of the counter, we can use an array by this format: 

```
array ( 
   visualizer_id = > counter ,
   ....
)
```

If you have any other suggestion, let me know

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/visualizer/pull/126
