### ISSUE TITLE
Desactivate library for members

### ISSUE THREAD

**Issue by antikah** [Codeinwp/visualizer#125]
Hi,

I would like to hide the Visualizer Library for members connected or initialise this plugin ONLY if an administrator or editor is connected.

But when I try to add a line like : 
if(current_user_can('editor') || current_user_can('administrator') ) { // code here } in the index.php of the pluggin, this crashes my site and I have to remove the code....

Does anybody can help me with this issue ?
Thanks in advance.

**Comment by UVLabs** [comment]
Hello, try wrapping the following lines in the code you have above:

https://github.com/Codeinwp/visualizer/blob/master/classes/Visualizer/Module/Admin.php#L301-L303

I don't believe there's a need to add the current_user_can administrator part because an admin has editor's privileges

**Comment by antikah** [comment]
Hello,

thank you for your answer but if I wrap this code, my administrator can't access to the visualizer anymore. I only want the admin to have access and no other member. For now, every members can see the menu. And if I wrap the code no one can see the menu.

**Comment by UVLabs** [comment]
Hello, it's not really a good idea to be editing those files because the changes would just be lost when the plugin updates. The code however should work, you replace the file with the one I attached in:

**wp-content\plugins\visualizer\classes\Visualizer\Module**

You need to grab the file from inside the zip folder

[Admin.zip](https://github.com/Codeinwp/visualizer/files/1053759/Admin.zip)

**Comment by antikah** [comment]
Hello,
When I replace that file, the site crashes and I cannot access to the wordpress dashboard anymore. The same case than when I did this in the index.php.
