### ISSUE TITLE
chart 2nd step not workin

### ISSUE THREAD

**Issue by selul** [Codeinwp/visualizer#152]
@contactashish13 using latest version from developm, on the chart building popup i get blank after i select the chart type

**Comment by contactashish13** [comment]
@selul I've fixed all instances where this could happen. Basically for unit tests exit() was replaced by wp_die() so now I'm checking if its a unit test case instance or not. 

PR: https://github.com/Codeinwp/visualizer/pull/153

**Comment by selul** [comment]
@contactashish13  https://drive.google.com/file/d/0B8cbkQkB9YbnRGNlaXdCUVhJY2s/view

please try to test more carefully, in order to avoid this back and forth.

**Comment by contactashish13** [comment]
@selul I tested it before I pushed in my changes. Please see: https://drive.google.com/open?id=0B_GLg3hHI3AzS19sNFhBT1VMdGM

**Comment by selul** [comment]
@contactashish13 and why this is not working ? 

Thanks !

**Comment by contactashish13** [comment]
@selul ok so the problem was that if pro is on (like it was on my instance), it works properly. Only when pro is deactivated does it not work. Have fixed it.  PR: https://github.com/Codeinwp/visualizer/pull/154

PS - the function visualizer_enable_track() in Module/Admin.php does not have comments so PHPCS is failing at my end. I'm still pushing in the changes.
