### ISSUE TITLE
conflict with acronix 

### ISSUE THREAD

**Issue by selul** [Codeinwp/visualizer#161]
@contactashish13 can you check this: 

this would be the problematic plugin
https://wordpress.org/plugins/arconix-faq/

**Comment by contactashish13** [comment]
@selul can you mention the bug?

**Comment by selul** [comment]
ah, sorry i thought i have added it.
https://wordpress.org/support/topic/conflict-with-acronix-faq-plugin/

**Comment by contactashish13** [comment]
@selul I've traced the error to line 273 in arconix-faq/includes/metabox/init.php. If we comment out the line that loads wp_enqueue_media(), there is no conflict. I dont know if there is an impact on arconix or not because I'm not sure what functionality that performs.

In visualizer code Visualizer/Module/Setup.php I've tried to dequeue the media scripts with different priorities but none of them work.

```
	public function __construct( Visualizer_Plugin $plugin ) {
		parent::__construct( $plugin );

		$this->_addAction( 'init', 'setupCustomPostTypes' );
		$this->_addAction( 'plugins_loaded', 'loadTextDomain' );
		$this->_addAction( 'admin_print_scripts', 'dequeue_media_conflicts', null, 9998 );
		$this->_addAction( 'admin_enqueue_scripts', 'dequeue_media_conflicts', null, 9998 );
		$this->_addAction( 'init', 'dequeue_media_conflicts', null, 9998 );
	}

    public function dequeue_media_conflicts() {
        wp_dequeue_script( 'media-upload' );
		wp_dequeue_script( 'media-editor' );
		wp_dequeue_script( 'media-audiovideo' );
		wp_dequeue_script( 'mce-view' );
		wp_dequeue_script( 'image-edit' );
		wp_dequeue_script( 'media-editor' );
		wp_dequeue_script( 'media-audiovideo' );
    }

```

Any suggestions?

**Comment by selul** [comment]
@contactashish13 is the acronix plugin including the media all over the admin ?

**Comment by contactashish13** [comment]
@selul yes, it does this in the init hook

**Comment by selul** [comment]
@contactashish13 then we can close this as their plugin is wrongly coded.
