### ISSUE TITLE
Some options don't work

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/visualizer#312]
Some options on some charts don't work. In the timeline chart, the title position, title color, axis title, font styles, legends...don't work.

Can they be made to work ( if Google supports ) or removed? @contactashish13 

PS: Can all the options be tested to see which one in the current one doesn't work and a list be posted here? I'm doing it on my side my a second eye will be helpful.

**Comment by mileamadalin** [comment]
@contactashish13 @HardeepAsrani 

I have tested all the charts:

1. Pie -- Works as expected 

https://drive.google.com/file/d/1oeFiX_AWxoa-YKe7UV9Phi_Zw86W3tv6/view

2. Line -- Works

https://drive.google.com/file/d/1zwnmMtW4tTq6nCWbcfF688muJaVorjf3/view

3. Area -- Works

https://drive.google.com/file/d/1ZE6MssmbYpe7jsjR9TaJdBxCmHmsGAF8/view

4. Geo -- Missing some features 

https://drive.google.com/file/d/1fW9QjMWzvBmG6xo1qZNa3c5WzH3Bvmqs/view

5. Bar -- Works 

https://drive.google.com/file/d/1UTM7aELOiuJM2lWq8O0AFQc-WCF8GvYA/view

6. Column -- Works

https://drive.google.com/file/d/1t6CEYJ8sG88dIzZpAU5NNlaPn1LtMtyv/view

7. Gauge -- A small visual bug -- Doesn't work 

https://drive.google.com/file/d/1SlwZQujH3g54dySVAkgmGwJrDrM8FPFG/view

Bug: 
![screenshot 2018-11-01 at 5 45 19 pm](https://user-images.githubusercontent.com/6906834/47862540-092a5100-ddfe-11e8-8355-2b78a4ec5037.png)

8. Scatter -- Works

https://drive.google.com/file/d/1vMBqnvNw7wpYchH_zAM8cQjKJfRM8paJ/view

9. Candlestick -- Works 

https://drive.google.com/file/d/1DI_cbbNf5XftAT_7P-XoqkDSLI5XNjh-/view

10. Table -- Doesn't work 

https://drive.google.com/file/d/1_b1o2eKyBWcJxsjl713NwtzLy3ATpUMI/view

11. Timeline -- Doesn't work 

https://drive.google.com/file/d/1ujJtTHH0IrEu6jBv9DB_kOQ7z7zJOFsc/view

12. Combo -- Works 

https://drive.google.com/file/d/1qqE7tKtyHhY1bDv_wn2HHrJX3ym6FWQ3/view

**Comment by contactashish13** [comment]
@mileamadalin apparently @HardeepAsrani is testing on Firefox. Can you check if that is the problem?

**Comment by mileamadalin** [comment]
@contactashish13 I have tested with FireFox and I faced the same issues. 

Geo -- Gauge -- Table -- Timeline -> Doesn't work

The rest of the charts works.

**Comment by contactashish13** [comment]
@mileamadalin  

Geo, Gauge, Table: This is not a missing feature - it mentions quite clearly `Text to display in the back-end admin area.`. This title is shown only in the library. This is different for other charts where it mentions `Text to display above the chart`. 

Have fixed the Gauge visual bug and problem with the Timeline options. Fixing the below as well as part of the same PRs:
- https://github.com/Codeinwp/visualizer/issues/319 
- https://github.com/Codeinwp/visualizer/issues/313

PRs: https://github.com/Codeinwp/visualizer/pull/332 and https://github.com/Codeinwp/visualizer-pro/pull/136


In the future, could you document the bugs in text as well so that there is no confusion? Just videos do not suffice especially when they are silent videos and leave scope for miscommunication.

**Comment by contactashish13** [comment]
@mileamadalin please verify these problem are no longer present with the new version and close this issue

**Comment by mileamadalin** [comment]
@contactashish13 I have checked, and I can confirm that the bugs were fixed
