### ISSUE TITLE
Timeline options not correctly mapped

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/visualizer#317]
All four Timeline options need to be inside a `timeline: {}` object.

```
showRowLabels
groupByRowLabel
colorByRowLabel
singleColor
```
Also needs to be mapped correctly for Gutenberg block.

@contactashish13 @selul

**Comment by contactashish13** [comment]
@HardeepAsrani you are correct but unfortunately that way does not work because for some reason it strictly expects true/false values which we are unable to send from PHP. That is why these lines https://github.com/Codeinwp/visualizer/blob/master/js/render-google.js#L97. You will have to find a way around it for Gutenberg unfortunately.
