### ISSUE TITLE
Possible issue with Customization JS file

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/visualizer#384]
@contactashish13 a user reported usthat we defined two file paths:

 one generic/default
`$file = $wp_filesystem->wp_content_dir() . 'uploads/visualizer/customization.js';`
and another specific
`$specific = $uploads['baseurl'] . '/visualizer/customization.js';`

and when we test the existence of these files, we return the path of the specific one:

```
if ( $wp_filesystem->is_readable( $file ) ) {
	return $specific;
}
```

and here is his recommendation: 

```
if ( $wp_filesystem->is_readable( $specific ) ) {
	return $specific;
}
		
if ( $wp_filesystem->is_readable( $file ) ) {
	return $default;
}
```

Ticket link: https://wordpress.org/support/topic/customization-js-with-404-error/#post-11353196

**Comment by contactashish13** [comment]
@mileamadalin it would be best to test this new code against the the intent of the original code. The original code gives the user a template JS file as part of the plugin and then copies this template JS file into the WP uploads folder so that changes can be made by the user to **that** instead of the file inside the plugin folder. This is because the user's changes should not get overwritten by our updates. 

Can you check for the original behavior vs. with the changed code?

**Comment by contactashish13** [comment]
closing this for lack of response + this is probably related to #498
