### ISSUE TITLE
Add datatable assets locally

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/visualizer#440]
We should load dataTable assets from the plugin instead of CDN as it makes it hard for the plugin to work offline.

@contactashish13

**Comment by contactashish13** [comment]
@selul what do you think about this? CDN better or local? @HardeepAsrani says the WP theme review team has strict rules about CDNs. What about the plugin review team? 

Whats our usual stance on this?

@DanyCaissy maybe you want to weigh in too?

**Comment by selul** [comment]
@contactashish13 I would have it locally in the plugin files for the next reasons: 

1) As Hardeep stated, it might be a good idea to work offline. 
2) For privacy reasons due to the fact that we don't know what kind of data the CDN collect related to their visitors. 
3) Freeze the dataTable js to a certain version. It might happen that the js file to get modified ( a new version release ) and the code that we have in the plugin to no longer work with this.

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/visualizer/pull/445
