### ISSUE TITLE
Data changes cancel previous design changes

### ISSUE THREAD

**Issue by DanyCaissy** [Codeinwp/visualizer#509]
![canceled-design-changes](https://user-images.githubusercontent.com/5183243/63735413-5cfe9e80-c845-11e9-8c54-2d813897a8f7.gif)

If you modify a chart's design, then modify the data in any way, the design will be reset to before you modified the design.

Note that this happens visually (the preview chart), but the correct design settings are saved if the user decides to save right after modifying the data.

This bug might confuse and/or frustrate users.

**Comment by contactashish13** [comment]
@DanyCaissy this is part of the whole UX/UI redo. I'm sure it will confuse first time users but I guess users have either got used to this or have not faced this. We can keep this in the UX revamp bucket that we need to address at some point in time anyway.

**Comment by contactashish13** [comment]
@DanyCaissy this change is not going to be possible. This is because of a conflict between the settings and the data. Consider the following scenario:

### scenario 1 - pie chart with 5 slices
- The color of slice 5 is changed
- A new file is now uploaded that has only 4 slices
- This updates the sidebar because now only 4 slices (instead of 5) should show under the Slices tab
- Now if the settings should remain the same as before, then the slices will also become 5 instead of 4. 

### scenario 2 - pie chart with 5 slices
- The pie hole is changed to 1 and color of slice 4 is changed
- A new file is now uploaded that has only 4 slices
- This updates the sidebar because now only 4 slices (instead of 5) should show under the Slices tab
- Now if we selectively update the settings to what the user had changed it to before changing the data, the pie hole will become 1 **but the slices data will not change**. Settings will get partially updated. This will cause confusion.

In the race between data and settings, the former should be given precedence. Most users will first update the data and then the settings. I see very few scenarios where a setting is changed and then the data is changed. This is a niche case that is better handled by an appropriate message that will make the user aware that if they need to change both, it has to be data first and then the settings and not the other way around.

**Comment by DanyCaissy** [comment]
@contactashish13 

I think I see what you mean. In that case, I think we need to find some kind of alternative to prevent that issue.

One potential solution I can see: If the design has been modified in any way, we could have a popup before editing the data that says something like:

"You have unsaved changes to the design, before modifying the data, you must save those changes first. Do you still want to do so?"

Buttons:
"Save Changes & Edit" - "Cancel"

Would that solve the issue?

**Comment by contactashish13** [comment]
Will fix this as part of #655

**Comment by rodica-andronache** [comment]
for me, it's working ok

**Comment by DanyCaissy** [comment]
@contactashish13 @rodica-andronache 

I think this helps. I also think we could go further and restrict the user entirely from the source tab until they've saved the chart. The message makes sense for us, but I think it will confuse some users who don't understand this specific limitation.

I'd suggest to simplify it to this:

"You've modified the chart's settings. To modify the data again, you must save this chart and re-open it for editing."

Additionally, we would remove the 'Cancel' button, and the 'Ok' button would do what the cancel button did. Meaning the user will not be allowed to modify the data at all after they modified the settings.

**Comment by contactashish13** [comment]
@DanyCaissy we can't presume that they want to stick by the changes they made. Maybe they made a change in the settings, changed their mind and then went to change the data. We should not stop them from doing so. I feel as long as we are notifying them, it's good. If they want to risk it despite that, it's their mistake to make.

I've changed the message as suggested to `You have modified the chart's settings. To modify the source/data again, you must save this chart and reopen it for editing. If you continue without saving the chart, you may lose your changes.`

PR https://github.com/Codeinwp/visualizer/pull/678

**Comment by DanyCaissy** [comment]
That's fine
