### ISSUE TITLE
"Total" row does not appear at the bottom of the table chart

### ISSUE THREAD

**Issue by purplecodes** [Codeinwp/visualizer#603]
When creating a table chart, the 'Total' is alphabetized and does not appear at the bottom.

Screencast: https://www.loom.com/share/44bac320956949ef98224d7481b14f13

Steps to replicate:
1. Created a new table chart
2. Imported the CSV file provided by the user
3. The 'Total' row appears three rows from the bottom as it is alphabetized

Lite version: 3.3.4
Ticket:  https://secure.helpscout.net/conversation/1027073299/209982?folderId=212385

**Comment by contactashish13** [comment]
@purplecodes what do you think the behavior should be? 

PS - @Codeinwp/support please always mention the error and the expected result.

**Comment by SilviuDinu** [comment]
@purplecodes the data table type of chart will sort the fields alphabetically (by default). In order to make sure it respects the order given in the CSV, we can check the Disable Sorting option from Advanced Settings.

I tried to make a video that will help to explain better -> https://share.vidyard.com/watch/u98CFHKNsEgPhMCno4ErDr?

@contactashish13 we can wait until the client responds to make sure there isn't any issue with his Disable Sorting option and then I think we can close this.

**Comment by purplecodes** [comment]
@SilviuDinu 

I missed this setting. Thanks for pointing that out. I tested and it did place the 'Total' row at the bottom of the table. I guess we can close it now.
