### ISSUE TITLE
add support for boolean data type in table charts

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/visualizer#677]
ref https://wordpress.org/support/topic/check-or-cross-in-a-table/

**Comment by contactashish13** [comment]
adding this to the current release so that current user woes can be addressed by the time #524 is ready,

**Comment by contactashish13** [comment]
### Previous behavior
Boolean values (true/false) added to the table are displayed as-is

### New behavior 
With PR https://github.com/Codeinwp/visualizer/pull/685 boolean values can be assigned a display value (a symbol or an HTML snippet) and that display value will show instead of the boolean value.

![image](https://user-images.githubusercontent.com/12953439/80452578-3351c600-8944-11ea-8322-338ece725ca8.png)

**Comment by rodica-andronache** [comment]
@contactashish13 everything's working well in Visualizer. 
I was just thinking that it would need some updates in the PRO version as well, as right now, when you edit the content from the Gutenberg block, the Column disappears and you can't set the custom values for true and false anymore https://www.loom.com/share/66ec034722164ded96849dcb3a259b3e

**Comment by contactashish13** [comment]
@rodica-andronache my testing shows that what you have pointed out seems to be a problem when you edit **any** chart in the block editor. Can you please confirm and create a new issue for this?

**Comment by rodica-andronache** [comment]
@contactashish13 not sure exactly what you mean by any chart. I've seen this only for the new boolean type fields. If I edited a column with a different type, that column did not disappear.
I think the problem is related to the new boolean data type.
I've also seen that if I edit the chart in the editor, and try to change one of the columns from type number to type boolean, the entire block breaks. If I change it to date type, for example, it works well
https://www.loom.com/share/94277acda9bb4020b950034da70ec24d

**Comment by contactashish13** [comment]
@rodica-andronache I'm sorry I meant it happens for any table chart. The last column disappears after you edit it using the the editor. I can reproduce this even on the master branch. Do you not see this behavior?

![Capture](https://user-images.githubusercontent.com/12953439/81254028-a1367580-9047-11ea-91d9-839791391177.JPG)

**Comment by rodica-andronache** [comment]
@contactashish13 yes, you are right, it's happening for the last column, no matter of its type. I'll create an issue about it, and release the update
