### ISSUE TITLE
Bubble chart legend position don't work in Gutenberg editor

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/visualizer#771]
### Description:

When i try to change the `Legend position` of the `Bubble chart` in Gutenberg editor, the control doesn't change at all.
I tried to change the position from dashboard, and all positions work fine except `Left of the chart` -> https://prnt.sc/uqm2hj
### How to reproduce:

1. Create a bubble chart and add it to a post.
2. Try to change the Legend position from the editor.

### Expected behaviour:
The control should work.
### Current behaviour:
The control doesn't change at all.
### Reference:

https://www.loom.com/share/8eba1ba1c8104b5fa40213ca0db9d8c2
### Technical info
* WordPress version: 5.5.1
* Plugin version: 3.4.8

**Comment by contactashish13** [comment]
@irinelenache As mentioned https://developers.google.com/chart/interactive/docs/gallery/bubblechart#configuration-options, `left` will work only under certain considerations:

![image](https://user-images.githubusercontent.com/12953439/98071586-f97cf180-1e89-11eb-888a-e75187c3bc27.png)

So, in order to avoid complications, I have removed `left` as an option.

Have fixed the issue you see with the gutenberg editor

PR https://github.com/Codeinwp/visualizer/pull/777
