### ISSUE TITLE
Charts won't render when aded inside infinite scrolls

### ISSUE THREAD

**Issue by cristian-ungureanu** [Codeinwp/visualizer#890]
### Description:
Based on https://github.com/Codeinwp/neve-pro-addon/issues/1899 we need a solution for charts that are not rendering when they're loaded via infinite scroll.
For Neve, we added the `neve-next-post-load` event after a post is added so maybe we can start by making Visualizer working with Neve

### Expected behaviour:
Charts to load when a new post is added via infinite scroll

### Current behaviour:
Charts are not rendered

### Reference:
https://github.com/Codeinwp/neve-pro-addon/issues/1899

### Technical info
* WordPress version: 5.9.2
* Plugin version: 2.2.0

**Comment by girishpanchal30** [comment]
@cristian-ungureanu it is possible by adding/triggering the below script in neve-pro-addon when XMLHttpRequest request is completed. 

```
var viz = Object.assign(visualizer, window.visualizer || {});
if(id){
    viz.id = id;
}
$('body').trigger('visualizer:render:chart:start', viz);
```

I have tried to render charts with Visualizer plugin in the neve them when infinite scrolls call but it is not possible in the visualizer plugin because of the next post comes with help of XMLHttpRequest(Ajax) request.

cc @selul

**Comment by cristian-ungureanu** [comment]
I don't think it will work as I saw that Visualizer only loads the JS scripts if there is a chart on the page. If I start from a post that doesn't have a chart, this might not work 🤔

**Comment by selul** [comment]
@girishpanchal30 Visualizer has this issue with any infinite scroll issue since is not taking into account that charts can be rendered dynamically. The solution needs be in Visualizer code, and this event `neve-next-post-load` helps you.

**Comment by girishpanchal30** [comment]
@selul Let me check with `neve-next-post-load` event and I'll update you here...

**Comment by girishpanchal30** [comment]
@cristian-ungureanu @selul I need your help here...
Should I enqueue the visualizer script in the post single page? because It's not possible to load charts without scripts.
I have implemented some ideas to load charts when the user is scrolling but the solution is not working when the visualizer script is not enqueued in a single page.
Ref: https://www.loom.com/share/ec700b50e5804f7483bc25d1b76a716f?sharedAppSource=personal_library

Please advise.
Thanks

**Comment by selul** [comment]
@girishpanchal30 can't you trigger the render when that event occurs?

**Comment by girishpanchal30** [comment]
@selul I can trigger but it will work only if the visualizer script is enqueued in the page.

**Comment by selul** [comment]
ah, that makes sense. I won't add the script if the chart is not present on the page since it will add a performance hit for pages where we won't embed charts. 

What I would do: 

1. Make sure that if the script is loaded, we have the fix in place by triggering the render.
2. Create a Tweak plugin that can be shared with the @Codeinwp/support  and force loading the script on every page. 

In this way, we will offer a way of fixing this edge case.

**Comment by girishpanchal30** [comment]
@selul Can you please create a new repo and share it with me so I can push new Tweak plugin on Github?

**Comment by selul** [comment]
@girishpanchal30 no need to createa. new repo, you can attach the zip here.

**Comment by girishpanchal30** [comment]
@selul @cristian-ungureanu Here is the attached tweak plugin zip file, please check and do let me know if you have any issues.
Plugin Zip: https://github.com/Codeinwp/visualizer/files/8380900/visualizer-infinite-scrolls.zip
Thanks

**Comment by cristian-ungureanu** [comment]
Thank you! I'll have a look and let you know.

**Comment by cristian-ungureanu** [comment]
@girishpanchal30 We should check if Visualizer is installed first. If it's not, the plugin throws a fatal error:

`Fatal error: Uncaught Error: Class 'Visualizer_Module_Frontend' not found`

**Comment by irinelenache** [comment]
@girishpanchal30 Tested and the fix doesn't change anything for me, the issue still happens

You can check it on this instance:
```
 Admin area URL: https://buzzwing.s4-tastewp.com/wp-admin 
 Username: irinel 
 Password: F-lNKVYSz68 
```

**Comment by girishpanchal30** [comment]
@irinelenache Please test with the latest attached plugin zip
https://github.com/Codeinwp/visualizer/files/8409182/visualizer-infinite-scrolls-04-03-2022.zip

**Comment by irinelenache** [comment]
@girishpanchal30 Checked again, here is what i found:

- [ ] On the test instance that i provided, if i open the post that will have the **Hello world** post as next, the charts won't load anymore and i'm getting some error in console https://vertis.d.pr/DStMtU

Besides that, it seems to work fine 👍

**Comment by girishpanchal30** [comment]
@irinelenache Fixed above mentioned issue, please test with the latest zip
https://github.com/Codeinwp/visualizer/files/8415202/visualizer-infinite-scrolls-05-05-2022.zip
Thanks

**Comment by irinelenache** [comment]
@girishpanchal30 Tested again and now everything works fine, thank you 👍

**Comment by girishpanchal30** [comment]
Hey @vytisbulkevicius,

I've checked and fixed  the issue in the attached zip. Please check and do let me know if have any issues.
[visualizer-infinite-scrolls-15-12-2022.zip](https://github.com/Codeinwp/visualizer/files/10235712/visualizer-infinite-scrolls-15-12-2022.zip)

Thanks
