### ISSUE TITLE
Charts do not have unique value for "post_title" column in the database "wp_posts" table

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/visualizer#915]
### Description:
One of the clients communicated an interesting request that we hadn't encountered before.
He's using Advanced Custom Fields (ACF) plugin to build a custom solution where a chart can be assigned to a user via ACF. The problem that he's facing is that Charts are stored as Posts in the DB and this is how he gets a list of charts - 
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/36594177/182018631-4e3881f1-1924-4184-b513-1abd2a9b0aae.png">

But then, in the dropdown of the results or charts appear with the same name:
<img width="1399" alt="image" src="https://user-images.githubusercontent.com/36594177/182018551-e6874f3a-38a3-490b-88d0-ab4d6c6a27f7.png">

This happens because in the database we save every chart with the same name for "post_title":
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/36594177/182018582-11eacb3a-b866-44df-abe6-ad853cf0481b.png">

Can we have unique naming for chart here (could be ID of the chart) without breaking something how charts currently works?

### Alternatives:
Try to guess which chart you want to select.

Reported here - https://secure.helpscout.net/conversation/1958630731/330707/

**Comment by girishpanchal30** [comment]
Hey @vytisbulkevicius,

> Can we have unique naming for chart here (could be ID of the chart) without breaking something how charts currently works?

Yes, I have created a unique title using title + ID using WordPress filter, Please check and let me know if you have an issue.

Thanks

**Comment by irinelenache** [comment]
@girishpanchal30 Tested and the enhancement seems to work fine 🚀 

Found something else, it happens with the live version of Visualizer also, but maybe it can be fixed in this PR:

If i create a chart, make a copy of it and try to edit one of them (the initial chart or the copy), when i click on **Save chart**, the screen freezes and i have to refresh the page to make it work. I created a video to better outline the issue https://vertis.d.pr/s6P5Wm . If the problem needs more attention, i can create a new issue for it 👍

**Comment by girishpanchal30** [comment]
@irinelenache Fixed above mentioned issue, Please check with the latest changes.

**Comment by irinelenache** [comment]
@girishpanchal30 Tested and the mentioned issue is fixed now, thank you 🚀
